### ISSUE TITLE
Can't fire openPrompt function

### ISSUE THREAD

**Issue by vitorfreitas** [pwa-builder/pwa-install#15]
**Describe the bug**
When I try to use `openPrompt` function I get "Cannot read property 'icons' of undefined" error on console.

**To Reproduce**
```jsx
<pwa-install id="pwa"></pwa-install>

...

document.querySelector('#pwa').openPrompt()
```

**Expected behavior**
Open "install pwa" prompt.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Google Chrome
 - Version: 78.0.3904.87

**Comment by jgw96** [comment]
Hello @vitorfreitas , thanks for opening an issue (: . This error was being thrown because this component expects certain basic parts of the web manifest to be there, including atleast one icon. However, I considered this a bug because the component did nothing to let you know that was the issue, an error was just thrown. To fix this I made this commit https://github.com/pwa-builder/pwa-install/commit/b53a1da8538fa4adb6db65941b1567815507fb04 which adds better error handling and will now throw an informative error message telling you what is missing and if the manifest cannot be read. Thanks for using the pwa-install component!

**Comment by vitorfreitas** [comment]
Great job, @jgw96! I'll try the solution and gonna let you know if it works!

**Comment by vitorfreitas** [comment]
Figured out that it has something about the time the function is called. I tried to run with a setTimeout to 5s and the popup appeared as expected
