### ISSUE TITLE
Install button should not disappear on cancel

### ISSUE THREAD

**Issue by christianliebel** [pwa-builder/pwa-install#224]
**Describe the bug**
When the user clicks _Cancel_ in the install prompt, the install button disappears. It should *only* disappear when the user clicks _Install_. 

**To Reproduce**
1. Go to a pwa-install enabled website
2. Click on the _Install_ button within the website
3. Click on _Install <title>_ in the pwa-install dialog box
4. Click on _Cancel_ in the install prompt
5. The _Install_ button within the website disappears

**Expected behavior**

The install button should not disappear

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 80

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jgw96** [comment]
Hello! Unfortunately, this is outside of our control right now as the prompt where you are hitting the cancel button is browser UI, not UI we have control over. When you hit the cancel button it gets rid of the install event too, which is why our button disappears as you would no longer be able to install for that session. We are however working with web standards to see if we can improve the APIs we have available for install to fix issues like these. Thanks for opening an issue with us!

**Comment by christianliebel** [comment]
Hi there! I’m not entirely sure if that’s really the case… feel free to check my demo here: https://pwapraxis.liebel.io/ ("App installieren"). You can click the install button (which uses the same event) to show the prompt again, no matter how often you cancel the browser’s prompt.
