### ISSUE TITLE
[Question]Install button Missing

### ISSUE THREAD

**Issue by qz2rg4** [pwa-builder/pwa-install#232]
I don't know if I am missing something here but the install button is missing on the popup. Only Cancel button

Please advise 

![image](https://user-images.githubusercontent.com/4931185/78914490-bc36b980-7a8a-11ea-9cb2-6610f318de83.png)

**Comment by jgw96** [comment]
Hello @qz2rg4 , what browser are you running this in? Also, if this is Edge or Chrome, do you see a plus icon in the url bar when you are on your PWA?

**Comment by qz2rg4** [comment]
Hi @jgw96 thanks for getting back to me. 

I'm running this in chrome and no plus sign.

It is a proof of concept app and it can be found here https://pwa.interon.co.za/

Thanks

**Comment by jgw96** [comment]
No problem! So the reason you are not getting the install button or the plus icon is because you are missing a 512x512 version of your icon in your manifest, you can use https://pwabuilder.com to generate one if you dont, just click on the edit manifest button once you put your URL in. Once you have added a 512x512 icon size your PWA will be ready to install. I am going to close this for now, but feel free to reply if you have any more questions, im happy to guide.
