### ISSUE TITLE
[FEATURE] Add I18n for pwa install

### ISSUE THREAD

**Issue by rdhainaut** [pwa-builder/pwa-install#274]
**Is your feature request related to a problem? Please describe.**
I have a web app with multiple locale (en, fr, ...)
The pwa install button show a description and features list (based on manifest.json) but i would like show a translated content. 

**Describe the solution you'd like**
Is it possible to add a locale file or json object (key locale, value translated) to show the dialog popup with the description and features description in the user locale ?

**Describe alternatives you've considered**
For the moment I have not other solution ...

**Comment by jgw96** [comment]
Hey @rdhainaut ! So this is not something that the pwa-install component handles itself, but it is something I thought of in the design! If you look at the properties the component takes https://github.com/pwa-builder/pwa-install#properties, all of the text in the component should be covered by those properties. What this means is that the component can easily take translated strings from your I18n service and display them. The reason this component does not handle this directly is because its out of the scope of this component. Because of this I am going to close this issue for now but @rdhainaut feel free to respond if you have any more questions and I will do my best to answer them (:

**Comment by rdhainaut** [comment]
@jgw96 Thanks for the feedback.  Indeed, you have totally right.  It s simpler and more flexible to delegate the translation to a i18n service.  

I have just not realised that properties could be override directly on the component (i thought that these value was readed exclusively from manifest file but i was wrong).

**Comment by jgw96** [comment]
No problem at all! Let me know if you have any more questions 😊
