### ISSUE TITLE
Button doesn't show and serviceworker returns 404

### ISSUE THREAD

**Issue by xererske** [pwa-builder/pwa-install#385]
Love your functionalities. Just what I am looking for, to create that amazing ux! 
There are a few things that don't yet work at my side and I am hoping that someone could help me out..

**1. The install button doesn't show.**

I tried adding both the npm and script module (seperately) for the pwainstall module.
Currently I have it like this:
```
    <script
        type="module"
        src="https://cdn.jsdelivr.net/npm/@pwabuilder/pwainstall">
    </script>
```
My html looks like this:
```
<pwa-install 
  showopen
  manifestpath="https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/manifest.json">
</pwa-install>
```

Shouldn't the button already appear? Or am I missing something?

**2. Serviceworker returns 404 error**

I get this return in the console on loading the page:
```
A bad HTTP response code (404) was received when fetching the script.
pwaupdate:176 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://maarten-van-wersch-development.bettywebblocks.com/') with script ('https://maarten-van-wersch-development.bettywebblocks.com/pwabuilder-sw.js'): A bad HTTP response code (404) was received when fetching the script.
```
I think the problem here is related to the fact that it is trying to get the pwabuilder-sw.js from 'https://maarten-van-wersch-development.bettywebblocks.com/pwabuilder-sw.js', when it actually is at 'https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/pwabuilder-sw.js'. 
Already tried to update my manifest.json with a serviceworker object but that didn't do the trick. 

manifest.json:
```
{
  "name": "Enabl",
  "short_name": "Enabl",
  "lang": "nl-NL",
  "description": "Freelanceplatform om vraag en aanbod te matchen!",
  "start_url": "https://maarten-van-wersch-development.bettywebblocks.com/platform/login",
  "scope": "https://maarten-van-wersch-development.bettywebblocks.com/platform/",
  "display": "standalone",
  "theme_color": "#FFF",
  "background_color": "#FFF",
  "url": "https://maarten-van-wersch-development.bettywebblocks.com/platform/login",
  "screenshots": [],
  "orientation": "portrait",
  "serviceworker": {
    "src": "https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/pwabuilder-sw.js",
    "scope": "/platform/"
  },
  "icons": [
    {
      "src": "https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/manifest_150x150",
      "sizes": "150x150",
      "type": "image/png"
    },
    {
      "src": "https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/manifest_512x512",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files/manifest_197x197",
      "sizes": "197x197",
      "type": "image/png"
    }
  ]
}
```

pwabuilder-sw.js:
```
// This is the "Offline copy of assets" service worker

const CACHE = 'pwabuilder-offline';
const QUEUE_NAME = 'bgSyncQueue';

importScripts(
  'https://storage.googleapis.com/workbox-cdn/releases/5.0.0/workbox-sw.js'
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

const bgSyncPlugin = new workbox.backgroundSync.Plugin(QUEUE_NAME, {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

workbox.routing.registerRoute(
  new RegExp('/*'),
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: CACHE,
    plugins: [bgSyncPlugin],
  })
);
```

Thanks!

**Comment by iang0ld** [comment]
Also the button doesn't show in the demo on Edge or Firefox.  That has stopped my from going further as it looks this component doesn't work.  Is seems to only work in Chrome.

**Comment by lee-leonardo** [comment]
@xererske 
Could I get a url from you to repro this issue? I suspect it has to do with a combination of your hosting service and some resource cache on your browser. Within this component we are using browser based functionality to install applications.

**Comment by iang0ld** [comment]
Sorry. Wrote my own.

**Comment by xererske** [comment]
@iang0ld what did you write?

**Comment by iang0ld** [comment]
I got this from the net and modified it.

<a id="btnInstall" title="Install onto your Home Screen" style="display:none"><i class="fal fa-mobile-android-alt"></i>&nbsp;&nbsp;Install App</a>

<script>
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker
                .register('/pwabuilder-sw.js')
                .then(function () { console.log('Service Worker Registered'); });
        }

        // Listen for the beforeinstallprompt event
        let deferredPrompt;
        window.addEventListener('beforeinstallprompt', (e) => {
            // Prevent the mini-infobar from appearing on mobile
            e.preventDefault();
            // Stash the event so it can be triggered later.
            deferredPrompt = e;
            // Update UI notify the user they can install the PWA
            showInstallPromotion();
        });

        // In-app installation flow
        btnInstall.addEventListener('click', (e) => {
            // Hide the app provided install promotion
            hideMyInstallPromotion();
            // Show the install prompt
            deferredPrompt.prompt();
            // Wait for the user to respond to the prompt
            deferredPrompt.userChoice.then((choiceResult) => {
                if (choiceResult.outcome === 'accepted') {
                    console.log('User accepted the install prompt');
                } else {
                    console.log('User dismissed the install prompt');
                }
            });
        });

        // Detect when the PWA was successfully installed
        window.addEventListener('appinstalled', (evt) => {
            // Log install to analytics
            console.log('INSTALL: Success');
        });

        // Track how the PWA was launched
        window.addEventListener('DOMContentLoaded', () => {
            let displayMode = 'browser tab';
            if (navigator.standalone) {
                displayMode = 'standalone-ios';
                hideMyInstallPromotion();
            }
            if (window.matchMedia('(display-mode: standalone)').matches) {
                displayMode = 'standalone';
                hideMyInstallPromotion();
            }
            /*
            else if (deferredPrompt == undefined) {
                // not a PWA
                hideMyInstallPromotion();
            }
            */
            // Log launch display mode to analytics
            console.log('DISPLAY_MODE_LAUNCH:', displayMode);
        });

        // Track when the display mode changes
        window.addEventListener('DOMContentLoaded', () => {
            window.matchMedia('(display-mode: standalone)').addListener((evt) => {
                let displayMode = 'browser tab';
                if (evt.matches) {
                    displayMode = 'standalone';
                }
                // Log display mode change to analytics
                console.log('DISPLAY_MODE_CHANGED', displayMode);
            });
        });

        function showInstallPromotion() {
            document.getElementById('btnInstall').style.display = "block";
        }

        function hideMyInstallPromotion() {
            document.getElementById('btnInstall').style.display = "none";
        }
    </script>

**Comment by lee-leonardo** [comment]
@iang0ld your issue is different than the listed issue above. Thanks for your input, if you wish to propose a change you can open an issue or create a pull request. But @xererske could I get a url for testing purposes so that I can better understand the issue you are seeing?

**Comment by xererske** [comment]
@lee-leonardo https://craftsmen-dev.bettywebblocks.com/

**Comment by xererske** [comment]
@lee-leonardo 
Wrong url..
This is the one: https://maarten-van-wersch-development.bettywebblocks.com/

**Comment by lee-leonardo** [comment]
@xererske digging into it more, it looks like how bettyblocks is serving up assets will impact how you are able to access those resources. For instance at the time of checking this issue the path to your assets folder is:

`https://assets.bettyblocks.com/fa2497488ee941968145a08cfed91a61_assets/files`

The hash definitely will change from time to time so if there's some environment variable that reflects the hash that probably will be safer.

Also the issue is with the pwa-update component, not this one.
https://github.com/pwa-builder/pwa-update#properties

This update component which you are importing has the ability to define where the service worker resides (e.g. `swpath`).

Also I don't see a service worker in the folder you've mentioned above, photo for your convenience. That's an easy fix. If you have any other questions, just @ me!

<img width="577" alt="Screen Shot 2020-08-26 at 9 51 57 AM" src="https://user-images.githubusercontent.com/6520001/91333000-d34c1e80-e781-11ea-8b5c-f191726455e0.png">

**Comment by xererske** [comment]
@lee-leonardo 
Thanks for your answer.
Still it doesn't work for me. Could you check my url: https://www.enabl.works/

Also the not showing button is still a mystery to me. Could this be caused by the service worker script? Shouldn't it already work?

Thanks

**Comment by lee-leonardo** [comment]
@xererske 
Your service worker will not work until you register the component, the pwa-update component takes care of that, but it needs to know where your service worker is. The same with the manifest with the pwa-install component.

Your hash has changed, meaning that url you used to serve the service worker is invalid now. The other 

Returning a 404: https://www.enabl.works/pwabuilder-sw.js
This is because your default path in the pwa-update component is not specified.

This is where your files are being served up now:
<img width="483" alt="Screen Shot 2020-09-02 at 6 30 08 PM" src="https://user-images.githubusercontent.com/6520001/92061152-61a83d80-ed4a-11ea-849c-fb1680301d00.png">

So the path to those files is now this:
https://assets.bettyblocks.com/a556ca2be5a340e4973dfc2af1657a2d_assets/files

This is the path your component is looking for:
<img width="563" alt="Screen Shot 2020-09-02 at 6 31 20 PM" src="https://user-images.githubusercontent.com/6520001/92061269-af24aa80-ed4a-11ea-8739-a4f2e6c5643f.png">

The pwa-install button is not showing for the same reason. This is the location of your manifest at the moment, recall the hash changing issue I mentioned earlier:
https://assets.bettyblocks.com/a556ca2be5a340e4973dfc2af1657a2d_assets/files/manifest.json?_=5e8e4758d1b4c1c35c0417e31fc51023

Since this url has changed, your site cannot pick up where to look for the manifest and thus is failing to work.

Does that make sense?
