### ISSUE TITLE
[Question] What's the best way to "wait" for the install button to appear?

### ISSUE THREAD

**Issue by aaronfc** [pwa-builder/pwa-install#434]
**Question in detail**
I am trying to figure out what is the best way to wait for the install button to appear, so that I can then show a proper "banner" or not.

**Is your question related to a problem? Please describe.**
Currently there are some times when the Install button won't appear (I am still investigating the reason for this) and some other times when the button appears but after a small delay. Currently the button appears in a banner I have at the bottom of the page accompanied by a text like "Haven't you installed us yet? [INSTALL BUTTON]".
What I want to achieve is to show the banner **only** if the install button is shown.

**Describe alternatives you've considered**
I am considering to put some "setTimeout" mechanism so that I check every X milliseconds if the button has appeared or not but I do not like very much the approach.

**Comment by lee-leonardo** [comment]
@aaronfc 
There is a `usecustom` flag for you to take over the styling and presentation of the component or how it interact with your app. Using your custom component and a js reference to the component, you should then be able to interact with the methods section of the component.

The inconsistency of when the banner shows could be due to a lot of different reasons, google has a good guide on creating a more consistent install experience. https://developers.google.com/web/fundamentals/primers/service-workers/registration

**Comment by jgw96** [comment]
Hello all! The install button will only show once the onBeforeInstallPrompt event is fired by the browser https://github.com/pwa-builder/pwa-install/blob/master/src/pwa-install.ts#L606 . Unfortunately (and this is something im discussing with the Edge team) Chromium is very inconsistent on when that event fires, but we can only show the install button after that fires as the `prompt` method (https://github.com/pwa-builder/pwa-install/blob/master/src/pwa-install.ts#L724) is  on that event object. Because of that, I am going to close this for now as a "notfix" as we are limited by the browser. Thanks!
