### ISSUE TITLE
Research improvements around the Safari experience

### ISSUE THREAD

**Issue by dfabulich** [pwa-builder/pwa-install#7]
Open https://pwainstall.glitch.me in iOS Safari 13.2.2 (but the version doesn't much matter) and click the Install button.

Actual: The install screen launches with a "Close" button, just like issue #6

Expected: An Install button; when you click it, it should give the user browser-specific directions on how to manually install the PWA, like this https://github.com/cubiq/add-to-homescreen

**Comment by benjibuiltit** [comment]
This library (and installable PWA's in general) rely rather heavily on Chrome at the moment due to `beforeinstallprompt`. See ["beforeinstallprompt" browser compatibility.](https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent#Browser_compatibility)

This results in some nuanced behavior based on browsers. For instance, as a Chrome user I would prefer that if I were [ineligible for installing a PWA](https://developers.google.com/web/fundamentals/app-install-banners#criteria), the install button is simply not shown. It would save me the click/confusion to see a modal with only a cancel button.

I can see where it may be necessary to create browser filters for certain behaviors using something like [bowser](https://github.com/lancedikson/bowser) and then handle these cases accordingly. In other words, the lack of a `deferredprompt` will mean different things based on the user's browser -- ineligible user vs. lack of browser support.

I'd like to propose adding a showeligible attribute to the component, that only shows the install button when a user is eligible on supported browsers. I'm happy to tackle this as well if it's agreed upon.

**Comment by bennypowers** [comment]
Most users will probably come here asking "does it support iOS?"

IMHO the component should provide some banner UI for a2hs for iOS users, and preferably lazy-loaded so sites can skip serving that code to capable browsers.

**Comment by jgw96** [comment]
Hey everyone! So there are two pieces here I want to cover. First, the iOS experience is something we are working on, you can follow my progress here https://github.com/pwa-builder/pwa-install/tree/ios . We are going to show a banner on Safari that leads the user through how to install a PWA to their homescreen on iOS. Would that cover what you are looking for @bennypowers ? Also, @benjibuiltit , I agree that a `showelegible` attribute would be awesome for this component. Also, thanks for offering to contribute that, we would love your help! Would you like to open an issue for this feature? Once an issue is open we can use that to track work. Also, before you get started id recommend checking out our contributing guide https://github.com/pwa-builder/pwa-install/blob/master/CONTRIBUTING.md . Thanks again!

**Comment by bennypowers** [comment]
> We are going to show a banner on Safari that leads the user through how to install a PWA to their homescreen on iOS.

Exactly what I'd expect this to do (short of staging a sit in at Apple campus)

Thanks 👍

**Comment by jgw96** [comment]
@bennypowers good to hear!

**Comment by jgw96** [comment]
Update on this issue: the latest release includes a 1.0 of this. There are a few last things I want to do, like ensure things work well on iPads etc. Getting close!

**Comment by dfabulich** [comment]
The "1.0" implementation is just text instead of a button. The text says, "Tap the share button and then 'Add to Homescreen'"

I claim that these instructions aren't sufficient to get users to victory here, and that over-the-shoulder usability testing would show a very low success rate.

Specifically, I suggest a Starbucks usability test here. Buy a Starbucks gift card, go to Starbucks, walk up to a bunch of people in line, and offer people a gift card if they're willing to test your website for you. Someone will agree; pull them aside, give them the gift card, direct them to pwainstall.glitch.me, and say "Follow the instructions on this website to install the app." See how likely they are to succeed.

I predict with a test like this, you'll get less than 20% success rate. Here's why.

* The share button doesn't say "Share" on it, so users wouldn't know to click on it by that name.
* The "Add to Homescreen" option isn't visible above the fold when you click the Share icon. You have to scroll down to find it.
* If you have to scroll down on the modal to get to the instructions, the Share button is no longer visible. Users would have to intuit that they need to scroll up to reveal the URL bar and footer bar, and then click the Share button.

My suggestions:
1. Use the iOS Share glyph (the box with an arrow coming out of it) in the UI, instead of describing it as "the share button"
1. Include a clickable button in pwa-install UI that uses [`navigator.share`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) to open the Share dialog.
1. Include an inline animated GIF or video demonstrating how to share. This will be pretty hard work, because it will have to support various different iOS versions, sometimes even different iOS minor versions. And that work may never be finished; it will be ongoing maintenance work for years. (There's a reason that https://github.com/cubiq/add-to-homescreen is no longer supported.) But I doubt that anything less than this will work.

**Comment by jgw96** [comment]
Hey @dfabulich (: I wanted to update you here. I have removed this issue from the the 1.0 milestone but am adding this to a 2.0 milestone. As far as using the share glyph instead of "The share button": To support translations simply and to improve accessibility we chose to not use an icon for this. This text is still something we are doing research on as a whole, so expect this to evolve. 

Your second suggestion is definitely something we are going to look into for 2.0, now that web share is in stable safari this might be a good user experience (: 

As far as #3 goes, this is a good goal but is outside the scope of this component and would unfairly harm performance for a large percentage of users + being a maintenance nightmare as you mention. 

I really appreciate all your suggestions and your passion on this subject, let me know what you think 😊

**Comment by jgw96** [comment]
Hey all, just wanted to post another update here! The latest release (1.2.5) fixed the final iOS issue which was that we were not detecting the iPad pro correctly and therefore we were showing the wrong UI for that device. After discussing with the team before the holidays, this is as far as we want to take the iOS experience right now as we are not sure what the future of installing PWAs from Safari looks like at the moment (more info: https://github.com/w3c/manifest/issues/835) . Because of this I am going to close this issue for now. We really appreciate all the feedback here and we will continue to watch the status of that issue.
